branch-defaults:
  master:
    environment: intern-cms-dev
global:
  application_name: intern-cms
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
