branch-defaults:
  minor_css:
    environment: show-nyc
global:
  application_name: show-nyc
  default_ec2_keyname: code_key
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 running Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
